/******************************************************************************/
/*           Generated by IBExpert 2026.2.22.1 01/03/2026 15:22:04            */
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES WIN1252;

CREATE DATABASE 'localhost/3050:C:\ProjetoSAG-Delphi-BD\database\BANCO_DADOS.FDB'
USER 'SYSDBA' PASSWORD 'masterkey'
PAGE_SIZE 16384
DEFAULT CHARACTER SET WIN1252 COLLATION WIN1252;



/******************************************************************************/
/*                                 Generators                                 */
/******************************************************************************/

CREATE GENERATOR GEN_LOTE_ID START WITH 1 INCREMENT BY 1;
SET GENERATOR GEN_LOTE_ID TO 27;

CREATE GENERATOR GEN_MORTALIDADE_ID START WITH 1 INCREMENT BY 1;
SET GENERATOR GEN_MORTALIDADE_ID TO 29;

CREATE GENERATOR GEN_PESAGEM_ID START WITH 1 INCREMENT BY 1;
SET GENERATOR GEN_PESAGEM_ID TO 27;



/******************************************************************************/
/*                                 Exceptions                                 */
/******************************************************************************/

CREATE EXCEPTION ERR_VALIDACAO 'Valor inválido ou acima do permitido para este lote!';



/******************************************************************************/
/*                             Stored procedures                              */
/******************************************************************************/



SET TERM ^ ;

CREATE PROCEDURE ST_INSERIR_MORTALIDADE (
    P_OBSERVACAO VARCHAR(255),
    P_QTD_MORTA INTEGER,
    P_DATA_MORTALIDADE DATE,
    P_ID_LOTE_FK INTEGER)
RETURNS (
    OUT_PERCENTUAL_ACUMULADO NUMERIC(15,2))
AS
BEGIN
  SUSPEND;
END^





SET TERM ; ^



/******************************************************************************/
/*                                   Tables                                   */
/******************************************************************************/



CREATE TABLE TAB_LOTES_AVES (
    ID_LOTE             INTEGER NOT NULL,
    DESCRICAO           VARCHAR(100) NOT NULL,
    DATA_ENTRADA        DATE NOT NULL,
    QUANTIDADE_INICIAL  INTEGER NOT NULL
);

CREATE TABLE TAB_MORTALIDADE (
    ID_MORTALIDADE    INTEGER NOT NULL,
    ID_LOTE_FK        INTEGER NOT NULL,
    DATA_MORTALIDADE  DATE NOT NULL,
    QUANTIDADE_MORTA  INTEGER NOT NULL,
    OBSERVACAO        VARCHAR(255)
);

CREATE TABLE TAB_PESAGEM (
    ID_PESAGEM         INTEGER NOT NULL,
    ID_LOTE_FK         INTEGER NOT NULL,
    DATA_PESAGEM       DATE NOT NULL,
    PESO_MEDIO         NUMERIC(10,2) NOT NULL,
    QUANTIDADE_PESADA  INTEGER NOT NULL
);



/******************************************************************************/
/*                                Primary keys                                */
/******************************************************************************/

ALTER TABLE TAB_LOTES_AVES ADD CONSTRAINT PK_TAB_LOTES_AVES PRIMARY KEY (ID_LOTE);
ALTER TABLE TAB_MORTALIDADE ADD CONSTRAINT PK_TAB_MORTALIDADE PRIMARY KEY (ID_MORTALIDADE);
ALTER TABLE TAB_PESAGEM ADD CONSTRAINT PK_TAB_PESAGEM PRIMARY KEY (ID_PESAGEM);


/******************************************************************************/
/*                                Foreign keys                                */
/******************************************************************************/

ALTER TABLE TAB_MORTALIDADE ADD CONSTRAINT FK_MORTALIDADE_LOTE FOREIGN KEY (ID_LOTE_FK) REFERENCES TAB_LOTES_AVES (ID_LOTE);
ALTER TABLE TAB_PESAGEM ADD CONSTRAINT FK_PESAGEM_LOTE FOREIGN KEY (ID_LOTE_FK) REFERENCES TAB_LOTES_AVES (ID_LOTE);


/******************************************************************************/
/*                                  Triggers                                  */
/******************************************************************************/



SET TERM ^ ;



/******************************************************************************/
/*                            Triggers for tables                             */
/******************************************************************************/



/* Trigger: TRG_BI_TAB_LOTES_AVES */
CREATE TRIGGER TRG_BI_TAB_LOTES_AVES FOR TAB_LOTES_AVES
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID_LOTE IS NULL OR NEW.ID_LOTE = 0) THEN
    NEW.ID_LOTE = NEXT VALUE FOR GEN_LOTE_ID;
END^

/* Trigger: TRG_BI_TAB_MORTALIDADE */
CREATE TRIGGER TRG_BI_TAB_MORTALIDADE FOR TAB_MORTALIDADE
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID_MORTALIDADE IS NULL OR NEW.ID_MORTALIDADE = 0) THEN
    NEW.ID_MORTALIDADE = NEXT VALUE FOR GEN_MORTALIDADE_ID;
END^

/* Trigger: TRG_BI_TAB_PESAGEM */
CREATE TRIGGER TRG_BI_TAB_PESAGEM FOR TAB_PESAGEM
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID_PESAGEM IS NULL OR NEW.ID_PESAGEM = 0) THEN
    NEW.ID_PESAGEM = NEXT VALUE FOR GEN_PESAGEM_ID;
END^

SET TERM ; ^



/******************************************************************************/
/*                             Stored procedures                              */
/******************************************************************************/



SET TERM ^ ;

ALTER PROCEDURE ST_INSERIR_MORTALIDADE (
    P_OBSERVACAO VARCHAR(255),
    P_QTD_MORTA INTEGER,
    P_DATA_MORTALIDADE DATE,
    P_ID_LOTE_FK INTEGER)
RETURNS (
    OUT_PERCENTUAL_ACUMULADO NUMERIC(15,2))
AS
declare variable v_qtd_inicial integer;
declare variable v_total_morto_anterior integer;
BEGIN

  SELECT QUANTIDADE_INICIAL FROM TAB_LOTES_AVES 
  WHERE ID_LOTE = :p_id_lote_fk 
  INTO :v_qtd_inicial;


  SELECT COALESCE(SUM(QUANTIDADE_MORTA), 0) FROM TAB_MORTALIDADE 
  WHERE ID_LOTE_FK = :p_id_lote_fk 
  INTO :v_total_morto_anterior;


  IF ((v_total_morto_anterior + p_qtd_morta) > v_qtd_inicial) THEN
    EXCEPTION ERR_VALIDACAO;


  INSERT INTO TAB_MORTALIDADE (ID_LOTE_FK, DATA_MORTALIDADE, QUANTIDADE_MORTA, OBSERVACAO)
  VALUES (:p_id_lote_fk, :p_data_mortalidade, :p_qtd_morta, :p_observacao);


  out_percentual_acumulado = ((CAST(v_total_morto_anterior + p_qtd_morta AS DOUBLE PRECISION) / v_qtd_inicial) * 100);
  
  SUSPEND; 
END^




SET TERM ; ^
